"use client";

import { useEffect, useState } from "react";
import { CheckCircle2, Download, PhoneCall, RotateCw } from "lucide-react";
import { Button } from "@/components/ui/button";
import type { QualifiedCallDashboardDay } from "@/lib/qualified-call-dashboard";
import { groupQualifiedCallDaysByWeek } from "@/lib/qualified-call-dashboard-weeks";

type DashboardPayload = {
  timeZone?: string;
  today?: string;
  days?: QualifiedCallDashboardDay[];
  error?: string;
};

function formatDay(value: string, timeZone: string) {
  const date = new Date(`${value}T12:00:00.000Z`);
  return new Intl.DateTimeFormat("en-US", {
    timeZone,
    weekday: "short",
    month: "short",
    day: "numeric",
    year: "numeric",
  }).format(date);
}

function formatQualifiedTime(value: string, timeZone: string) {
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return value;
  return new Intl.DateTimeFormat("en-US", {
    timeZone,
    hour: "numeric",
    minute: "2-digit",
    second: "2-digit",
    hour12: true,
    timeZoneName: "short",
  }).format(date);
}

function taskDetailHref(taskId: string, callId: string | null) {
  const params = new URLSearchParams({ from: "dashboard" });
  if (callId) params.set("callId", callId);
  return `/tasks/${encodeURIComponent(taskId)}?${params.toString()}`;
}

function formatShortDate(value: string, timeZone: string) {
  return new Intl.DateTimeFormat("en-US", {
    timeZone,
    month: "numeric",
    day: "numeric",
  }).format(new Date(`${value}T12:00:00.000Z`));
}

function escapeHtml(value: string | null | undefined) {
  return (value || "").replace(/[&<>"']/g, (character) => ({
    "&": "&amp;",
    "<": "&lt;",
    ">": "&gt;",
    '"': "&quot;",
    "'": "&#39;",
  })[character] || character);
}

function exportWeekAsPdf(input: {
  days: QualifiedCallDashboardDay[];
  timeZone: string;
  label: string;
}) {
  const popup = window.open("", "_blank", "width=1120,height=800");
  if (!popup) return;
  const total = input.days.reduce((sum, day) => sum + day.total, 0);
  const rows = input.days.flatMap((day) => day.callers.flatMap((caller) => caller.calls.map((call) => `
    <tr>
      <td>${escapeHtml(caller.name)}</td>
      <td>${escapeHtml(formatQualifiedTime(call.qualifiedAt, input.timeZone))}</td>
      <td>${escapeHtml(call.brandName || call.taskTitle)}</td>
      <td>${escapeHtml(call.taskTitle)}</td>
      <td>${escapeHtml(call.reviewerName || call.reviewerEmail || "Not recorded")}</td>
      <td>${escapeHtml(call.callId || "Not linked")}</td>
    </tr>`)));
  popup.document.write(`<!doctype html>
<html><head><meta charset="utf-8" /><title>Qualified calls - ${escapeHtml(input.label)}</title>
<style>
  @page { size: A4 landscape; margin: 15mm; }
  * { box-sizing: border-box; }
  body { color: #172033; font-family: Arial, Helvetica, sans-serif; font-size: 11px; margin: 0; }
  header { align-items: end; display: flex; justify-content: space-between; margin-bottom: 28px; }
  h1 { font-size: 25px; letter-spacing: -0.8px; margin: 0; }
  .period { color: #596579; font-size: 12px; margin-top: 6px; }
  .total { color: #582dc6; font-size: 30px; font-weight: 700; text-align: right; }
  .total-label { color: #596579; font-size: 10px; text-align: right; }
  table { border-collapse: collapse; width: 100%; }
  th { background: #f3f0ff; color: #4c278f; font-size: 10px; letter-spacing: 0.3px; padding: 10px 8px; text-align: left; }
  td { border-bottom: 1px solid #e7e9ee; padding: 10px 8px; vertical-align: top; }
  tr { break-inside: avoid; }
  footer { color: #7b8495; font-size: 9px; margin-top: 18px; }
</style></head><body>
<header><div><h1>Qualified calls</h1><div class="period">${escapeHtml(input.label)} · ${escapeHtml(input.timeZone)}</div></div><div><div class="total">${total}</div><div class="total-label">Current Qualified</div></div></header>
<table><thead><tr><th>Caller</th><th>Qualified at</th><th>Brand</th><th>Task</th><th>AccountManager</th><th>Call record</th></tr></thead><tbody>${rows.join("")}</tbody></table>
<footer>Generated by Super FollowUP</footer>
<script>window.onload = () => window.print();</script></body></html>`);
  popup.document.close();
}

function DashboardLoading() {
  return (
    <div className="mx-auto max-w-3xl px-1 py-1">
      <div className="h-9 w-36 animate-pulse rounded-lg bg-slate-200" />
      <div className="mt-10 h-28 animate-pulse rounded-3xl bg-slate-200/70" />
      <div className="mt-10 space-y-8">
        {[1, 2, 3].map((item) => <div key={item} className="h-20 animate-pulse rounded-2xl bg-slate-200/60" />)}
      </div>
    </div>
  );
}

async function requestDashboard() {
  const response = await fetch("/api/dashboard/qualified-calls");
  const payload = await response.json() as DashboardPayload;
  if (!response.ok) throw new Error(payload.error || "Unable to load dashboard");
  return payload;
}

export function QualifiedCallsDashboard() {
  const [data, setData] = useState<DashboardPayload | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [selectedWeekKey, setSelectedWeekKey] = useState<string | null>(null);

  const load = () => {
    setLoading(true);
    setError(null);
    requestDashboard()
      .then((payload) => setData(payload))
      .catch((reason: unknown) => setError(reason instanceof Error ? reason.message : "Unable to load dashboard"))
      .finally(() => setLoading(false));
  };

  useEffect(() => {
    let cancelled = false;
    void requestDashboard()
      .then((payload) => { if (!cancelled) setData(payload); })
      .catch((reason: unknown) => { if (!cancelled) setError(reason instanceof Error ? reason.message : "Unable to load dashboard"); })
      .finally(() => { if (!cancelled) setLoading(false); });
    return () => { cancelled = true; };
  }, []);

  if (loading) return <DashboardLoading />;

  if (error) {
    return (
      <div className="mx-auto flex min-h-[60vh] max-w-3xl flex-col items-start justify-center px-1">
        <h1 className="text-3xl font-bold tracking-[-0.04em] text-slate-950">Dashboard</h1>
        <p className="mt-3 text-sm text-slate-500">{error}</p>
        <Button className="mt-6" onClick={load}><RotateCw className="mr-2 size-4" />Try again</Button>
      </div>
    );
  }

  const allDays = data?.days || [];
  const timeZone = data?.timeZone || "America/New_York";
  const today = data?.today || allDays[0]?.date || "";
  const weeks = today ? groupQualifiedCallDaysByWeek(allDays, today) : [];
  const selectedWeek = weeks.find((week) => week.key === selectedWeekKey) || weeks[0];
  const days = selectedWeek?.days || [];
  const total = days.reduce((sum, day) => sum + day.total, 0);
  const weekLabel = selectedWeek
    ? `Week ${weeks.findIndex((week) => week.key === selectedWeek.key) + 1} · ${formatShortDate(selectedWeek.start, timeZone)}-${formatShortDate(selectedWeek.end, timeZone)}`
    : "Week";

  return (
    <div className="mx-auto max-w-3xl px-1 pb-10">
      <h1 className="text-3xl font-bold tracking-[-0.04em] text-slate-950">Dashboard</h1>

      {weeks.length ? (
        <div className="mt-5 flex items-center justify-between gap-3">
          <label className="sr-only" htmlFor="qualified-calls-week">Qualified calls week</label>
          <select
            id="qualified-calls-week"
            value={selectedWeek?.key || ""}
            onChange={(event) => setSelectedWeekKey(event.target.value)}
            className="h-10 min-w-64 bg-slate-100 px-3 text-sm font-semibold text-slate-800 outline-none focus:ring-2 focus:ring-violet-500"
          >
            {weeks.map((week, index) => (
              <option key={week.key} value={week.key}>
                Week {index + 1} · {formatShortDate(week.start, timeZone)}-{formatShortDate(week.end, timeZone)}
              </option>
            ))}
          </select>
          <Button
            className="h-10 shrink-0 bg-violet-700 px-4 hover:bg-violet-800"
            onClick={() => selectedWeek && exportWeekAsPdf({ days, timeZone, label: weekLabel })}
          >
            <Download className="mr-2 size-4" />Export PDF
          </Button>
        </div>
      ) : null}

      <div className="mt-8 flex items-end justify-between gap-5 bg-violet-50 px-5 py-6 sm:px-7">
        <span className="min-w-0">
          <span className="flex items-center gap-2 text-sm font-semibold text-violet-800"><CheckCircle2 className="size-4" />Qualified calls</span>
          <span className="mt-2 block text-5xl font-bold tracking-[-0.065em] text-slate-950">{total}</span>
        </span>
        <span className="pb-1 text-right text-xs font-medium text-slate-500">Current Qualified<br />{timeZone}</span>
      </div>

      {days.length ? (
        <div className="mt-10 space-y-10">
          {days.map((day) => (
            <section key={day.date} aria-label={`${formatDay(day.date, timeZone)} Qualified calls`}>
              <div className="flex items-baseline justify-between gap-4">
                <time className="text-sm font-semibold text-slate-900">{formatDay(day.date, timeZone)}</time>
                <span className="shrink-0 text-sm font-semibold text-violet-700">{day.total}</span>
              </div>
              <div className="mt-4 space-y-6">
                {day.callers.map((caller) => (
                  <div key={`${day.date}-${caller.id || "unassigned"}`} className="space-y-3">
                    <div className="flex items-center justify-between gap-4 px-1">
                      <span className="truncate text-sm font-semibold text-slate-800">{caller.name}</span>
                      <span className="shrink-0 text-sm font-semibold text-slate-500">{caller.total}</span>
                    </div>
                    <div className="space-y-1">
                      {caller.calls.map((call) => (
                          <a
                            key={call.taskId}
                            href={taskDetailHref(call.taskId, call.callId)}
                          className="group flex w-full items-start gap-3 px-1 py-3 text-left transition-colors active:scale-[0.99] hover:bg-white/70"
                        >
                          <span className="mt-1 grid size-8 shrink-0 place-items-center rounded-full bg-slate-100 text-slate-600 group-active:bg-violet-100 group-active:text-violet-700"><PhoneCall className="size-3.5" /></span>
                          <span className="min-w-0 flex-1">
                            <span className="block truncate text-sm font-semibold text-slate-900">{call.brandName || call.taskTitle}</span>
                            <span className="mt-1 block truncate text-xs text-slate-500">Task · {call.taskTitle}</span>
                            <span className="mt-1 block text-xs text-slate-500">AccountManager · {call.reviewerName || call.reviewerEmail || "Not recorded"}</span>
                            <span className="mt-1 block truncate text-xs text-slate-500">{formatQualifiedTime(call.qualifiedAt, timeZone)} · Call record {call.callId || "not linked"}</span>
                          </span>
                        </a>
                      ))}
                    </div>
                  </div>
                ))}
              </div>
            </section>
          ))}
        </div>
      ) : (
        <div className="mt-20 flex flex-col items-center text-center text-slate-500">
          <span className="grid size-12 place-items-center rounded-full bg-slate-100 text-slate-400"><CheckCircle2 className="size-5" /></span>
          <p className="mt-4 text-sm font-medium">No Qualified calls yet</p>
        </div>
      )}
    </div>
  );
}
