"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { ArrowLeft, Bomb, CalendarClock, CircleAlert, Phone, Plus, Send, UserRound } from "lucide-react";
import { toast } from "sonner";
import { useWorkspace } from "./workspace-store";
import { Channel, Contact, CPCode, dateOnly, uid } from "@/lib/outreach-domain";
import { Avatar, AvatarFallback } from "@/components/ui/avatar";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Textarea } from "@/components/ui/textarea";
import { InteractionFeed } from "./interaction-feed";

const show=(r:{ok:boolean;message:string})=>r.ok?toast.success(r.message):toast.error(r.message);
const CP=({value}:{value:string})=><Badge variant="outline" className="rounded-md bg-white font-mono text-[11px] font-bold">{value}</Badge>;
const Status=({value}:{value:string})=><Badge className={value.includes("Bomb")?"bg-blue-100 text-blue-700":value.includes("Human")||value.includes("Reply")?"bg-violet-100 text-violet-700":value.includes("Due")?"bg-amber-100 text-amber-700":"bg-slate-100 text-slate-700"}>{value}</Badge>;
const channelAvailable=(c:Contact,ch:Channel)=>ch==="Email"?!!c.email&&c.emailValid:ch==="Phone"||ch==="SMS"?!!c.phone&&c.phoneValid:ch==="WhatsApp"?!!c.whatsapp:ch==="LinkedIn"?!!c.linkedin:false;

export function BrandDetail({customerId}:{customerId:string}){
  const {state,can,pauseBrand,assignBrand,closeBrand}=useWorkspace();
  const router=useRouter(); const [timeline,setTimeline]=useState("All"); const [launch,setLaunch]=useState(false); const [reply,setReply]=useState(false); const [cp,setCP]=useState(false); const [follow,setFollow]=useState(false); const [call,setCall]=useState(false); const [contact,setContact]=useState(false); const [close,setClose]=useState(false); const [reason,setReason]=useState("");
  const c=state.customers.find(x=>x.id===customerId); if(!c)return <div className="grid min-h-[60vh] place-items-center"><div className="text-center"><CircleAlert className="mx-auto mb-3 size-8 text-slate-300"/><h1 className="font-bold">Brand not found</h1><Button variant="link" onClick={()=>router.push("/customers")}>Back to Brands</Button></div></div>;
  const interactions=state.interactions.filter(i=>i.customerId===c.id&&(timeline==="All"||timeline==="Messages"&&i.type==="Message"||timeline==="Phone"&&i.type==="Phone"||timeline==="Bomb"&&i.type==="Bomb"||timeline==="CP"&&i.type==="CP"||timeline==="Human"&&["Human","Follow-up"].includes(i.type))).sort((a,b)=>b.createdAt.localeCompare(a.createdAt));
  const instance=state.bombInstances.find(b=>b.id===c.activeBombId); const actions=instance?state.actions.filter(a=>a.bombInstanceId===instance.id):[]; const next=actions.filter(a=>a.status==="Scheduled").sort((a,b)=>a.actualDate.localeCompare(b.actualDate))[0]; const owner=state.users.find(u=>u.id===c.ownerId); const last=interactions[0];
  return <div className="mx-auto max-w-[1480px]"><button onClick={()=>router.push("/customers")} className="mb-5 inline-flex items-center gap-2 text-sm font-semibold text-slate-500 hover:text-slate-900"><ArrowLeft className="size-4"/>Brands</button><div className="mb-6 flex flex-wrap items-start justify-between gap-4"><div className="flex items-center gap-4"><Avatar className="size-14"><AvatarFallback className="bg-violet-100 font-bold text-violet-700">{c.initials}</AvatarFallback></Avatar><div><h1 className="text-2xl font-bold tracking-tight">{c.name}</h1><div className="mt-2 flex gap-2"><CP value={c.cp}/><Status value={c.status}/></div></div></div><div className="flex flex-wrap gap-2">{can("reply")&&<Button variant="outline" onClick={()=>setReply(true)}><Send className="mr-2 size-4"/>Send message</Button>}{can("launch")&&<Button variant="outline" onClick={()=>setLaunch(true)}><Bomb className="mr-2 size-4"/>Launch Bomb</Button>}{can("changeCP")&&<Button onClick={()=>setCP(true)}>Change CP</Button>}</div></div>
  <div className="mb-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{[["Current goal",state.cps.find(x=>x.code===c.cp)?.goal||"—"],["Last interaction",last?.title||"None"],["Next action",next?`${next.channel} · ${dateOnly(next.actualDate)}`:c.status==="Human Handling"?"Human reply":"No action"],["Next owner",c.status==="Bomb Running"?"System":c.status==="Human Handling"?owner?.name||"Unassigned":"—"],["Source",c.source]].map(([l,v])=><div key={l} className="rounded-xl border bg-white p-4"><div className="text-xs font-semibold uppercase tracking-wide text-slate-400">{l}</div><div className="mt-2 text-sm font-semibold">{v}</div></div>)}</div>
  <div className="grid gap-6 xl:grid-cols-[1fr_340px]"><section className="overflow-hidden rounded-2xl border bg-white"><div className="flex flex-wrap items-center justify-between gap-3 border-b p-5"><div><h2 className="font-bold">Brand timeline</h2><p className="text-xs text-slate-500">Every Contact, channel and complete exchange</p></div><Tabs value={timeline} onValueChange={setTimeline}><TabsList>{["All","Messages","Phone","Bomb","CP","Human"].map(x=><TabsTrigger key={x} value={x}>{x}</TabsTrigger>)}</TabsList></Tabs></div><InteractionFeed interactions={interactions} contacts={c.contacts}/></section>
  <aside className="space-y-5"><section className="rounded-2xl border bg-white p-5"><div className="flex items-center justify-between"><div><h2 className="font-bold">{instance?"Active Bomb":"Human handling"}</h2><p className="mt-1 text-xs text-slate-500">{instance?.templateName||"Automation is not currently active"}</p></div>{instance?<Bomb className="size-5 text-violet-600"/>:<UserRound className="size-5 text-violet-600"/>}</div>{instance?<div className="mt-5 space-y-3">{actions.map(a=><div key={a.id} className="flex items-center justify-between text-xs"><span>{a.channel}</span><Status value={a.status}/></div>)}</div>:<div className="mt-5 rounded-xl bg-slate-50 p-4 text-sm text-slate-600">Last: {last?.title||"No interaction"}<br/>Owner: {owner?.name||"Unassigned"}</div>}<div className="mt-4 grid grid-cols-2 gap-2"><Button variant="outline" size="sm" onClick={()=>setFollow(true)}><CalendarClock className="mr-2 size-3.5"/>Follow-up</Button><Button variant="outline" size="sm" onClick={()=>setCall(true)}><Phone className="mr-2 size-3.5"/>Call task</Button></div></section>
  <section className="rounded-2xl border bg-white p-5"><div className="flex items-center justify-between"><h2 className="font-bold">Contacts</h2>{can("editBrand")&&<Button variant="ghost" size="icon-sm" onClick={()=>setContact(true)}><Plus className="size-4"/></Button>}</div><div className="mt-3 space-y-3">{c.contacts.map(x=><div key={x.id} className="rounded-xl bg-slate-50 p-3"><div className="text-sm font-semibold">{x.name}</div><div className="mt-1 text-xs text-slate-500">{x.role} · {x.preferredChannel}</div><div className="mt-2 text-xs text-slate-600">{x.email||x.phone||"No channel"}</div></div>)}</div></section>
  {can("editBrand")&&<section className="rounded-2xl border bg-white p-5"><div className="text-sm font-bold">Ownership</div><Select value={c.ownerId||"unassigned"} onValueChange={v=>show(assignBrand(c.id,v))}><SelectTrigger className="mt-3 w-full"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="unassigned">Unassigned</SelectItem>{state.users.filter(u=>["Outreach Manager","Human Responder"].includes(u.role)).map(u=><SelectItem key={u.id} value={u.id}>{u.name}</SelectItem>)}</SelectContent></Select><div className="mt-3 grid grid-cols-2 gap-2"><Button variant="outline" size="sm" onClick={()=>show(pauseBrand(c.id))}>{c.status==="Paused"?"Resume":"Pause"}</Button><Button variant="outline" size="sm" className="text-rose-600" onClick={()=>setClose(true)}>Close</Button></div></section>}</aside></div>
  <LaunchBombDialog customerId={c.id} open={launch} onOpenChange={setLaunch}/><ReplyDialog customerId={c.id} open={reply} onOpenChange={setReply}/><ChangeCPDialog customerId={c.id} open={cp} onOpenChange={setCP}/><FollowUpDialog customerId={c.id} open={follow} onOpenChange={setFollow}/><CreateCallDialog customerId={c.id} open={call} onOpenChange={setCall}/><ContactDialog customerId={c.id} open={contact} onOpenChange={setContact}/><Dialog open={close} onOpenChange={setClose}><DialogContent><DialogHeader><DialogTitle>Close Brand?</DialogTitle><DialogDescription>This stops the active Bomb and resolves open Inbox items.</DialogDescription></DialogHeader><Textarea value={reason} onChange={e=>setReason(e.target.value)} placeholder="Closing reason"/><DialogFooter><Button variant="outline" onClick={()=>setClose(false)}>Cancel</Button><Button variant="destructive" onClick={()=>{show(closeBrand(c.id,reason||"No longer pursuing"));setClose(false)}}>Close Brand</Button></DialogFooter></DialogContent></Dialog></div>;
}

export function LaunchBombDialog({customerId,open,onOpenChange}:{customerId?:string;open:boolean;onOpenChange:(v:boolean)=>void}){const {state,launchBomb}=useWorkspace();const c=state.customers.find(x=>x.id===customerId);const bombs=state.bombs.filter(b=>b.status==="Active"&&b.cp===c?.cp);const [bombId,setBombId]=useState("");const selected=bombs.find(b=>b.id===bombId);const targets=c?.contacts.filter(x=>x.role===selected?.targetRole)||[];const [target,setTarget]=useState("");const unavailable=selected&&targets[0]?selected.steps.filter(s=>!channelAvailable(targets.find(t=>t.id===target)||targets[0],s.channel)).map(s=>s.channel):[];return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent><DialogHeader><DialogTitle>Launch Bomb</DialogTitle><DialogDescription>One snapshot will run for {c?.name}. Any meaningful reply stops it.</DialogDescription></DialogHeader><div className="space-y-4"><label className="text-sm font-medium">Bomb<Select value={bombId} onValueChange={v=>{setBombId(v);setTarget("")}}><SelectTrigger className="mt-2 w-full"><SelectValue placeholder="Select a Bomb"/></SelectTrigger><SelectContent>{bombs.map(b=><SelectItem key={b.id} value={b.id}>{b.name} · V{b.version}</SelectItem>)}</SelectContent></Select></label>{selected&&<><label className="text-sm font-medium">Target Contact<Select value={target||targets[0]?.id} onValueChange={setTarget}><SelectTrigger className="mt-2 w-full"><SelectValue placeholder={`Requires ${selected.targetRole}`}/></SelectTrigger><SelectContent>{targets.map(t=><SelectItem key={t.id} value={t.id}>{t.name} · {t.role}</SelectItem>)}</SelectContent></Select></label><div className="rounded-xl bg-slate-50 p-4 text-sm"><b>{selected.goal}</b><div className="mt-2 text-xs text-slate-500">{selected.steps.map(s=>s.channel).join(" → ")}</div>{unavailable.length>0&&<div className="mt-2 text-xs text-amber-700">Unavailable steps will be skipped: {[...new Set(unavailable)].join(", ")}</div>}</div></>}</div><DialogFooter><Button variant="outline" onClick={()=>onOpenChange(false)}>Cancel</Button><Button disabled={!selected||!targets.length} onClick={()=>{if(!c||!selected)return;const r=launchBomb(c.id,selected.id,target||targets[0]?.id);show(r);if(r.ok)onOpenChange(false)}}>Launch Bomb</Button></DialogFooter></DialogContent></Dialog>}

export function ReplyDialog({customerId,open,onOpenChange}:{customerId:string;open:boolean;onOpenChange:(v:boolean)=>void}){const {state,sendHumanReply}=useWorkspace();const c=state.customers.find(x=>x.id===customerId);const [contactId,setContact]=useState(c?.contacts[0]?.id||"");const contact=c?.contacts.find(x=>x.id===contactId)||c?.contacts[0];const options=(['Email','SMS','WhatsApp','LinkedIn'] as Channel[]).filter(ch=>contact&&channelAvailable(contact,ch));const [channel,setChannel]=useState<Channel>(contact?.preferredChannel||"Email");const [content,setContent]=useState("");return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent><DialogHeader><DialogTitle>Send message</DialogTitle><DialogDescription>An active Bomb will stop before this human message is sent.</DialogDescription></DialogHeader><div className="grid grid-cols-2 gap-3"><Select value={contact?.id} onValueChange={setContact}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{c?.contacts.map(x=><SelectItem key={x.id} value={x.id}>{x.name}</SelectItem>)}</SelectContent></Select><Select value={options.includes(channel)?channel:options[0]} onValueChange={v=>setChannel(v as Channel)}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{options.map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select></div><Textarea className="min-h-32" value={content} onChange={e=>setContent(e.target.value)} placeholder="Write a reply…"/><DialogFooter><Button variant="outline" onClick={()=>onOpenChange(false)}>Cancel</Button><Button disabled={!contact||!content.trim()} onClick={()=>{if(!contact)return;const r=sendHumanReply(customerId,contact.id,options.includes(channel)?channel:options[0],content);show(r);if(r.ok){setContent("");onOpenChange(false)}}}><Send className="mr-2 size-4"/>Send</Button></DialogFooter></DialogContent></Dialog>}

export function ChangeCPDialog({customerId,open,onOpenChange}:{customerId:string;open:boolean;onOpenChange:(v:boolean)=>void}){const {state,changeCP}=useWorkspace();const c=state.customers.find(x=>x.id===customerId);const [cp,setCP]=useState<CPCode>(c?.cp||"CP0");const [evidence,setEvidence]=useState("Latest contact interaction");const [note,setNote]=useState("");const stage=state.cps.find(x=>x.code===cp);return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent><DialogHeader><DialogTitle>Change Brand CP</DialogTitle><DialogDescription>CP never changes automatically. Review evidence and confirm.</DialogDescription></DialogHeader><Select value={cp} onValueChange={v=>setCP(v as CPCode)}><SelectTrigger className="w-full"><SelectValue/></SelectTrigger><SelectContent>{state.cps.map(x=><SelectItem key={x.code} value={x.code}>{x.code} · {x.name}</SelectItem>)}</SelectContent></Select><div className="rounded-xl bg-violet-50 p-4 text-sm text-violet-900"><b>Exit criteria</b><p className="mt-1">{stage?.criteria}</p></div><Input value={evidence} onChange={e=>setEvidence(e.target.value)} placeholder="Evidence"/><Textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Optional note"/><DialogFooter><Button variant="outline" onClick={()=>onOpenChange(false)}>Cancel</Button><Button disabled={cp===c?.cp||!evidence} onClick={()=>{const r=changeCP(customerId,cp,evidence,note);show(r);if(r.ok)onOpenChange(false)}}>Move to {cp}</Button></DialogFooter></DialogContent></Dialog>}

export function FollowUpDialog({customerId,open,onOpenChange}:{customerId:string;open:boolean;onOpenChange:(v:boolean)=>void}){const {state,createFollowUp}=useWorkspace();const [days,setDays]=useState("3");const [reason,setReason]=useState("");const [note,setNote]=useState("");return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent><DialogHeader><DialogTitle>Schedule follow-up</DialogTitle><DialogDescription>This creates a human reminder. Nothing is sent automatically.</DialogDescription></DialogHeader><Select value={days} onValueChange={setDays}><SelectTrigger className="w-full"><SelectValue/></SelectTrigger><SelectContent>{[["1","Tomorrow"],["3","In 3 days"],["5","In 5 days"],["7","In 7 days"]].map(x=><SelectItem key={x[0]} value={x[0]}>{x[1]}</SelectItem>)}</SelectContent></Select><Input value={reason} onChange={e=>setReason(e.target.value)} placeholder="Reason"/><Textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Note"/><DialogFooter><Button variant="outline" onClick={()=>onOpenChange(false)}>Cancel</Button><Button disabled={!reason.trim()} onClick={()=>{const r=createFollowUp(customerId,new Date(Date.parse(state.simulatedDate)+Number(days)*86400000).toISOString(),reason,note);show(r);if(r.ok)onOpenChange(false)}}>Schedule</Button></DialogFooter></DialogContent></Dialog>}

export function CreateCallDialog({customerId,open,onOpenChange}:{customerId:string;open:boolean;onOpenChange:(v:boolean)=>void}){const {state,createCallTask}=useWorkspace();const c=state.customers.find(x=>x.id===customerId);const valid=c?.contacts.filter(x=>x.phone&&x.phoneValid)||[];const [contact,setContact]=useState(valid[0]?.id||"");const [days,setDays]=useState("1");const [note,setNote]=useState("");return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent><DialogHeader><DialogTitle>Create Call Task</DialogTitle><DialogDescription>The capacity scheduler chooses the Caller and may move the date.</DialogDescription></DialogHeader><Select value={contact||valid[0]?.id} onValueChange={setContact}><SelectTrigger className="w-full"><SelectValue placeholder="Valid phone contact"/></SelectTrigger><SelectContent>{valid.map(x=><SelectItem key={x.id} value={x.id}>{x.name} · {x.phone}</SelectItem>)}</SelectContent></Select><Select value={days} onValueChange={setDays}><SelectTrigger className="w-full"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="0">Today</SelectItem><SelectItem value="1">Tomorrow</SelectItem><SelectItem value="3">In 3 days</SelectItem></SelectContent></Select><Textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Goal and context"/><DialogFooter><Button variant="outline" onClick={()=>onOpenChange(false)}>Cancel</Button><Button disabled={!valid.length} onClick={()=>{const r=createCallTask(customerId,contact||valid[0].id,new Date(Date.parse(state.simulatedDate)+Number(days)*86400000).toISOString(),note);show(r);if(r.ok)onOpenChange(false)}}>Create Task</Button></DialogFooter></DialogContent></Dialog>}

function ContactDialog({customerId,open,onOpenChange}:{customerId:string;open:boolean;onOpenChange:(v:boolean)=>void}){const {updateContact}=useWorkspace();const [name,setName]=useState("");const [role,setRole]=useState<Contact['role']>("Other");const [email,setEmail]=useState("");const [phone,setPhone]=useState("");return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent><DialogHeader><DialogTitle>Add Contact</DialogTitle><DialogDescription>Channel availability is derived from valid contact details.</DialogDescription></DialogHeader><Input value={name} onChange={e=>setName(e.target.value)} placeholder="Contact name"/><Select value={role} onValueChange={v=>setRole(v as Contact['role'])}><SelectTrigger className="w-full"><SelectValue/></SelectTrigger><SelectContent>{["Connector","Owner","Other"].map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select><Input value={email} onChange={e=>setEmail(e.target.value)} placeholder="Email"/><Input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="Phone"/><DialogFooter><Button variant="outline" onClick={()=>onOpenChange(false)}>Cancel</Button><Button disabled={!name} onClick={()=>{const r=updateContact(customerId,{id:uid('ct'),name,role,email:email||undefined,phone:phone||undefined,whatsapp:phone||undefined,preferredChannel:email?'Email':'Phone',emailValid:!!email,phoneValid:!!phone});show(r);if(r.ok)onOpenChange(false)}}>Save Contact</Button></DialogFooter></DialogContent></Dialog>}
